---
- name: install nginx package
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: install net-tools package
  apt:
    name: net-tools
    state: present
    update_cache: yes

- name: create nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: create streams dir
  file:
    path: /etc/nginx/streams-enabled
    state: directory

- name: remove nginx default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

#- name: letsencrypt setup and ssl reverse proxy
#  template:
#    src: proxy.public.node.conf.j2
#    dest: /etc/nginx/streams-enabled/public-node.conf
#    mode: 0600
#  when:
#    - is_public|default(false)|bool

- name: create proxy service file
  template:
    src: proxy.conf.j2
    dest: /etc/nginx/streams-enabled/polkadot-proxy.conf
    mode: 0600
  when:
    - enable_reverse_proxy|default(false)|bool or enableReverseProxy|default(false)|bool

- name: restart nginx service
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
