
- name: Remove default nginx config
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: Create self-signed certificate, if configured.
  command: >
    openssl req -x509 -nodes -subj '/O=Integritee Node' -days 365
    -newkey rsa:4096 -sha256 -keyout {{ item.key }} -out {{ item.cert }}
    creates={{ item.cert }}
  with_items: "{{ self_signed_certs }}"

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Install nginx site for node
  template:
    src: proxy.public.node.conf.j2
    dest: /etc/nginx/sites-enabled/node

- name: Reload nginx to activate specified site
  service:
    name: nginx
    state: restarted
