---
- name: check if keys already exist
  shell: |
    set -o pipefail
    if [ -d /home/polkadot/.local/share/polkadot/chains/{{ polkadot_network_id }}/keystore ]; then
      ls /home/polkadot/.local/share/polkadot/chains/{{ polkadot_network_id }}/keystore -1U | wc -l
    else
      mkdir -p /home/polkadot/.local/share/polkadot/chains/{{ polkadot_network_id }}/
      chown -R polkadot:polkadot /home/polkadot/.local/share/polkadot
      echo 0
    fi
  args:
    executable: /bin/bash
  register: keystore_files
  changed_when: False

- name: initialize server keys
  import_role:
    name: polkadot-rotate-keys
  when: keystore_files.stdout == "0"
