---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  flake8
platforms:
  - name: polkadot-update-binary-collator-node
    image: ubuntu:bionic
    groups:
      - collator
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      polkadot-update-binary-collator-node:
        polkadot_network_id: ksmcc3
        collator_binary_url: 'https://github.com/w3f/polkadot/releases/download/v0.8.23/polkadot'
        collator_binary_checksum: 'sha256:cdf31d39ed54e66489d1afe74ed7549d5bcdf8ff479759e8fc476d17d069901e'
verifier:
  name: testinfra
  lint:
    name: flake8
